[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
company_onchain = "5A3ZEMpudXKh5KMTuZoNesPGWpUoYuHnFKAhzYQoEeqH"

[programs.devnet]
company_onchain = "5A3ZEMpudXKh5KMTuZoNesPGWpUoYuHnFKAhzYQoEeqH"

[programs.mainnet]
company_onchain = "5A3ZEMpudXKh5KMTuZoNesPGWpUoYuHnFKAhzYQoEeqH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -t 1000000 tests/"
build = "anchor build"
deploy-local = "anchor deploy --provider.cluster localnet"
deploy-devnet = "anchor deploy --provider.cluster devnet"
deploy-mainnet = "anchor deploy --provider.cluster mainnet"

[test]
startup_wait = 15000
shutdown_wait = 2000
upgradeable = true

[test.validator]
url = "https://api.devnet.solana.com"
bind_address = "0.0.0.0"
rpc_port = 8899
ws_port = 8900
gossip_port = 8001
reset = true
limit_ledger_size = "50000000"
